spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ibk
    username: ibk
    password: i123b456k
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    enabled: true
    cache: false
server:
  port: 8025